//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FikiMedicalCentre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtkonsultasi
    {
        public int id_konsultasi { get; set; }
        public int id_obat { get; set; }
        public int jumlah { get; set; }
        public int harga_obat { get; set; }
    
        public virtual msobat msobat { get; set; }
        public virtual trkonsultasi trkonsultasi { get; set; }
    }
}
