//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FikiMedicalCentre.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FIKIEntities : DbContext
    {
        public FIKIEntities()
            : base("name=FIKIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dtkonsultasi> dtkonsultasis { get; set; }
        public virtual DbSet<msdokter> msdokters { get; set; }
        public virtual DbSet<msjadwaldokter> msjadwaldokters { get; set; }
        public virtual DbSet<mskaryawan> mskaryawans { get; set; }
        public virtual DbSet<msobat> msobats { get; set; }
        public virtual DbSet<mspasien> mspasiens { get; set; }
        public virtual DbSet<msrole> msroles { get; set; }
        public virtual DbSet<trkonsultasi> trkonsultasis { get; set; }
        public virtual DbSet<trpembayaran> trpembayarans { get; set; }
        public virtual DbSet<trpendaftaran_konsultasi> trpendaftaran_konsultasi { get; set; }
        public virtual DbSet<trpengambilan_obat> trpengambilan_obat { get; set; }
    }
}
