//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FikiMedicalCentre.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class msjadwaldokter
    {
        public int id_jadwal { get; set; }

        [DisplayName("Hari Praktek")]
        [Required(ErrorMessage = "Hari wajib diisi")]
        [StringLength(10)]
        public string hari { get; set; }

        [DisplayName("Waktu Mulai")]
        [Required(ErrorMessage = "Waktu mulai wajib diisi")]
        public System.TimeSpan waktu_awal { get; set; }

        [DisplayName("Waktu Akhir")]
        [Required(ErrorMessage = "Waktu akhir wajib diisi")]
        public System.TimeSpan waktu_akhir { get; set; }

        [DisplayName("Dokter")]
        [Required(ErrorMessage = "Dokter wajib diisi")]
        public int id_dokter { get; set; }

        [DisplayName("Status")]
        public int status { get; set; }

        public virtual msdokter msdokter { get; set; }
    }
}
