//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FikiMedicalCentre.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class mskaryawan
    {
        public int id_karyawan { get; set; }

        [DisplayName("Nama Karyawan")]
        [Required(ErrorMessage = "Nama karyawan wajib diisi")]
        [StringLength(50)]
        public string nama { get; set; }

        [DisplayName("Tempat Lahir")]
        [Required(ErrorMessage = "Tempat Lahir wajib diisi")]
        [StringLength(50)]
        public string tempat_lahir { get; set; }

        [DisplayName("Tanggal Lahir")]
        [Required(ErrorMessage = "Tanggal Lahir wajib diisi")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime tgl_lahir { get; set; }

        [DisplayName("Jenis Kelamin")]
        [Required(ErrorMessage = "Jenis Kelamin wajib diisi")]
        public string jenis_kelamin { get; set; }

        [DisplayName("Alamat")]
        [Required(ErrorMessage = "Alamat wajib diisi")]
        [StringLength(100)]
        public string alamat { get; set; }

        [DisplayName("No Telepon")]
        [Required(ErrorMessage = "No Telepon wajib diisi")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Hanya angka!")]
        [StringLength(13, ErrorMessage = "Maksimal 13 digit!")]
        public string no_telp { get; set; }

        [DisplayName("Email")]
        [Required(ErrorMessage = "Email wajib diisi")]
        [StringLength(50)]
        [RegularExpression(@"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$", ErrorMessage = "Format Email tidak valid!")]
        public string email { get; set; }

        [DisplayName("Role")]
        public int id_role { get; set; }

        [DisplayName("Username")]
        [Required(ErrorMessage = "Username wajib diisi")]
        [StringLength(20)]
        public string username { get; set; }

        [DisplayName("Password")]
        [Required(ErrorMessage = "Password wajib diisi")]
        [StringLength(20)]
        public string password { get; set; }

        [DisplayName("Status")]
        public int status { get; set; }


        public virtual msrole msrole { get; set; }
    }
}
