//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FikiMedicalCentre.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class msrole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public msrole()
        {
            this.msdokters = new HashSet<msdokter>();
            this.mskaryawans = new HashSet<mskaryawan>();
            this.mspasiens = new HashSet<mspasien>();
        }

        [DisplayName("Role")]
        public int id_role { get; set; }

        [DisplayName("Deskripsi Role")]
        [Required(ErrorMessage = "Deskripsi role wajib diisi")]
        [StringLength(100)]
        public string deskripsi { get; set; }

        [DisplayName("Status")]
        public int status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<msdokter> msdokters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mskaryawan> mskaryawans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mspasien> mspasiens { get; set; }
    }
}
