//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FikiMedicalCentre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trpembayaran
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public trpembayaran()
        {
            this.trpengambilan_obat = new HashSet<trpengambilan_obat>();
        }
    
        public int id_pembayaran { get; set; }
        public System.DateTime tgl_pembayaran { get; set; }
        public int id_konsultasi { get; set; }
        public long total_biaya { get; set; }
    
        public virtual trkonsultasi trkonsultasi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trpengambilan_obat> trpengambilan_obat { get; set; }
    }
}
