//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FikiMedicalCentre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trpendaftaran_konsultasi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public trpendaftaran_konsultasi()
        {
            this.trkonsultasis = new HashSet<trkonsultasi>();
        }
    
        public int id_daftar_konsultasi { get; set; }
        public System.DateTime tgl_daftar_konsultasi { get; set; }
        public int id_pasien { get; set; }
        public int id_dokter { get; set; }
        public string jenis_pembayaran { get; set; }
    
        public virtual msdokter msdokter { get; set; }
        public virtual mspasien mspasien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trkonsultasi> trkonsultasis { get; set; }
    }
}
