//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FikiMedicalCentre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trpengambilan_obat
    {
        public int id_ambil_obat { get; set; }
        public int id_pembayaran { get; set; }
        public int status { get; set; }
    
        public virtual trpembayaran trpembayaran { get; set; }
    }
}
